language: rust
cache: cargo
sudo: false
matrix:
  include:
    - rust: stable
    - rust: nightly
      env: FEATURES='combinators'
script: |
  cargo build --verbose --features "${FEATURES}"
  cargo test --verbose --features "${FEATURES}"
